site_name: Endstone
site_url: https://endstone.dev/
site_author: Vincent Wu

repo_name: EndstoneMC/endstone
repo_url: https://github.com/EndstoneMC/endstone
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2023 - 2024 Vincent Wu

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EndstoneMC
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/endstone
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/endstone
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/endstone_mc
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xxgPuc2XN9

  version:
    provider: mike
    default: stable
    alias: true

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized:
      enabled: !ENV [ CI, false ]
      enable_creation_date: true
      exclude:
        - reference/cpp/*
  - git-committers:
      enabled: !ENV [ CI, false ]
      repository: EndstoneMC/endstone
      branch: main
  - mkdocstrings:
      enabled: !ENV [ CI, false ]
      custom_templates: docs/templates
      handlers:
        python:
          paths: [ python/src ]
          load_external_modules: true
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
          options:
            # general options
            find_stubs_package: true
            show_bases: true
            show_source: false
            allow_inspection: false
            # headings options
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            # member options
            inherited_members: false
            filters: [ "!^_" ]
            merge_init_into_class: true
            # docstrings options
            show_if_no_docstring: true
            # signature/annotations options:
            annotations_path: brief
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            modernize_annotations: true
            summary: true
            # griffe extensions
            extensions:
              - griffe_endstone

  - mkdoxy:
      enabled: !ENV [ CI, false ]
      projects:
        "reference/cpp":
          src-dirs: include/endstone/
          full-doc: true
          doxy-cfg:
            FILE_PATTERNS: "*.h"
            EXCLUDE_PATTERNS: "*/detail/*"
            RECURSIVE: YES
            STRIP_FROM_INC_PATH: "include/"

theme:
  name: 'material'
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Start your server: getting-started/start-your-server.md
  - Tutorials:
      - Create your first plugin: tutorials/create-your-first-plugin.md
      - Install your plugin: tutorials/install-your-plugin.md
      - Use color codes: tutorials/use-color-codes.md
      - Register commands: tutorials/register-commands.md
      - Register event listeners: tutorials/register-event-listeners.md
      - Schedule tasks: tutorials/schedule-tasks.md
      - Publish your plugin: tutorials/publish-your-plugin.md

  - Reference:
      - reference/index.md
      - Python API:
          - Server: reference/python/server.md
          - Player: reference/python/player.md
          - Actor: reference/python/actor.md
          - Block: reference/python/block.md
          - Command: reference/python/command.md
          - Event: reference/python/event.md
          - Form: reference/python/form.md
          - Level: reference/python/level.md
          - Inventory: reference/python/inventory.md
          - Network: reference/python/network.md
          - Permissions: reference/python/permissions.md
          - Plugin: reference/python/plugin.md
          - Scoreboard: reference/python/scoreboard.md
          - Scheduler: reference/python/scheduler.md
          - Miscellaneous: reference/python/misc.md
      - C++ API:
          - Classes:
              - Class List: reference/cpp/annotated.md
              - Class Index: reference/cpp/classes.md
              - Class Hierarchy: reference/cpp/hierarchy.md
              - Class Members: reference/cpp/class_members.md
              - Class Member Functions: reference/cpp/class_member_functions.md
              - Class Member Variables: reference/cpp/class_member_variables.md
              - Class Member Typedefs: reference/cpp/class_member_typedefs.md
              - Class Member Enumerations: reference/cpp/class_member_enums.md
          - Namespaces:
              - Namespace List: reference/cpp/namespaces.md
              - Namespace Members: reference/cpp/namespace_members.md
              - Namespace Member Functions: reference/cpp/namespace_member_functions.md
              - Namespace Member Variables: reference/cpp/namespace_member_variables.md
              - Namespace Member Typedefs: reference/cpp/namespace_member_typedefs.md
              - Namespace Member Enumerations: reference/cpp/namespace_member_enums.md
          - Files:
              - File List: reference/cpp/files.md
              - File Functions: reference/cpp/functions.md
              - File Variables: reference/cpp/variables.md
              - File Macros: reference/cpp/macros.md

  - Changelog: changelog.md
