blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://endstone.dev/
    about: Check our documentation for guides, API reference, and tutorials
  - name: ğŸ’¬ Discord Community
    url: https://discord.gg/xxgPuc2XN9
    about: Chat with other Endstone users and developers
  - name: ğŸ Python Plugin Template
    url: https://github.com/EndstoneMC/python-plugin-template
    about: Get started quickly with a Python plugin template
  - name: ğŸ”§ C++ Plugin Template
    url: https://github.com/EndstoneMC/cpp-plugin-template
    about: Get started quickly with a C++ plugin template
