timestamp = 1771517583
version = "1.26.0"

[windows]
"BlockState::StateListNode::mHead" = 113262312
"Enchant::mEnchants" = 114125008
"getI18n::result" = 113498128
# Actor
"?teleportTo@Actor@@UEAAXAEBVVec3@@_NHH1@Z" = 59243168
# ActorFactory
"?createSpawnedActor@ActorFactory@@QEAA?AV?$OwnerPtr@VEntityContext@@@@AEBUActorDefinitionIdentifier@@PEAVActor@@AEBVVec3@@AEBVVec2@@@Z" = 59675920
# BedrockLog::LogDetails
"?_log_va@LogDetails@BedrockLog@@AEAAXW4LogAreaID@@IPEBDHH1PEAD@Z" = 91742784
# BlockDescriptor::ResolveHelper
"?resolve@ResolveHelper@BlockDescriptor@@QEAAX_N@Z" = 70775616
# BlockType
"?tryGetStateFromLegacyData@BlockType@@QEBAPEBVBlock@@G@Z" = 70557200
# BlockTypeRegistry
"?forEachBlockType@BlockTypeRegistry@@QEAAXV?$function_ref@$$A6A_NAEBVBlockType@@@Z$$A6A_N0@Z@brstd@@@Z" = 72908832
# CampfireBlockActor
"?_finishCooking@CampfireBlockActor@@AEAAXAEAVBlockSource@@H@Z" = 72764720
# Certificate
"?validate@Certificate@@QEAA_N_J_N1@Z" = 78181040
# Command
"?run@Command@@QEBAXAEBVCommandOrigin@@AEAVCommandOutput@@@Z" = 49627104
# CommandOriginLoader
"?load@CommandOriginLoader@@SA?AV?$unique_ptr@VCommandOrigin@@U?$default_delete@VCommandOrigin@@@std@@@std@@AEBVCompoundTag@@AEAVServerLevel@@@Z" = 49676032
# CommandRegistry
"?addEnumValues@CommandRegistry@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@3@@Z" = 49287936
"?describe@CommandRegistry@@AEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVCommandParameterData@@@Z" = 49300256
"?registerAlias@CommandRegistry@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z" = 49258800
"?registerCommand@CommandRegistry@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBDW4CommandPermissionLevel@@UCommandFlag@@3@Z" = 49256064
"?registerOverloadInternal@CommandRegistry@@AEAAXAEAUSignature@1@AEAUOverload@1@@Z" = 49264400
"?serializeAvailableCommands@CommandRegistry@@QEBA?AVAvailableCommandsPacket@@XZ" = 49310848
"?symbolToString@CommandRegistry@@AEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VSymbol@1@@Z" = 49306272
# CommandUtils
"?getActorName@CommandUtils@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActor@@@Z" = 49348048
# CraftingDataPacket
"?prepareFromRecipes@CraftingDataPacket@@SA?AV?$unique_ptr@VCraftingDataPacket@@U?$default_delete@VCraftingDataPacket@@@std@@@std@@AEBVRecipes@@_N@Z" = 29953984
# DedicatedServer
"?start@DedicatedServer@@QEAA?AW4StartResult@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActivationArguments@Bedrock@@@Z" = 1302608
# FurnaceBlockActor
"?getBurnDuration@FurnaceBlockActor@@SAMAEBVItemStackBase@@M@Z" = 7284880
# InventoryTransaction
"?executeFull@InventoryTransaction@@QEBA?AW4InventoryTransactionError@@AEAVPlayer@@_N@Z" = 68164272
# Item
"?readUserData@Item@@UEBAXAEAVItemStackBase@@AEAVIDataInput@@AEAVReadOnlyBinaryStream@@@Z" = 65359568
# ItemInstance
"?fromTag@ItemInstance@@SA?AV1@AEBVCompoundTag@@@Z" = 65424224
# ItemRegistry
"?lookupByName@ItemRegistry@@AEBA?AV?$WeakPtr@VItem@@@@AEAHV?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z" = 65141232
# ItemStackBase
"?_loadBlocksForCanPlaceOnCanDestroy@ItemStackBase@@CA_NAEAV?$vector@PEBVBlockType@@V?$allocator@PEBVBlockType@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z" = 65485504
"?init@ItemStackBase@@IEAAXHHH_N@Z" = 65442560
# LeavesBlock
"?_die@LeavesBlock@@IEBAXAEAVBlockSource@@AEBVBlockPos@@@Z" = 71144992
# Level
"?tick@Level@@UEAAXXZ" = 69835664
# LiquidBlock
"?_trySpreadTo@LiquidBlock@@IEBAXAEAVBlockSource@@AEBVBlockPos@@H1E@Z" = 71164096
# MapDataManager
"?_loadMapData@MapDataManager@@IEAAPEAVMapItemSavedData@@AEBUActorUniqueID@@@Z" = 70030368
# MinecraftCommands
"?compileCommand@MinecraftCommands@@QEAAPEAVCommand@@AEBVHashedString@@AEAVCommandOrigin@@W4CurrentCmdVersion@@V?$function@$$A6AXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@std@@@Z" = 49387296
"?executeCommand@MinecraftCommands@@QEBA?AUMCRESULT@@AEAVCommandContext@@_N@Z" = 49384736
# MinecraftPackets
"?createPacket@MinecraftPackets@@SA?AV?$shared_ptr@VPacket@@@std@@W4MinecraftPacketIds@@@Z" = 27126496
# Mob
"?knockback@Mob@@UEAAXPEAVActor@@HMMMMM@Z" = 60820656
# NetworkConnection
"?receivePacket@NetworkConnection@@QEAA?AW4DataStatus@NetworkPeer@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$shared_ptr@V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@@5@@Z" = 27054336
# NetworkSystem
"?send@NetworkSystem@@QEAAXAEBVNetworkIdentifier@@AEBVPacket@@W4SubClientId@@@Z" = 27124352
"?sendToMultiple@NetworkSystem@@QEAAXAEBV?$vector@UNetworkIdentifierWithSubId@@V?$allocator@UNetworkIdentifierWithSubId@@@std@@@std@@AEBVPacket@@@Z" = 27125440
# Pack
"?createPack@Pack@@SA?AV?$unique_ptr@VPack@@U?$default_delete@VPack@@@std@@@std@@AEBVIPackIOProvider@@AEBVResourceLocation@@W4PackType@@W4PackOrigin@@AEAVIPackManifestFactory@@V?$NonOwnerPointer@$$CBVIContentKeyProvider@@@Bedrock@@PEAVPackSourceReport@@AEBVPath@Core@@@Z" = 36874928
# PistonBlockActor
"?tick@PistonBlockActor@@UEAAXAEAVBlockSource@@@Z" = 73611328
# Player
"?completeUsingItem@Player@@QEAAXXZ" = 63432656
"?drop@Player@@UEAA_NAEBVItemStack@@_N@Z" = 63490176
"?startSleepInBed@Player@@UEAA?AW4BedSleepingResult@@AEBVBlockPos@@@Z" = 63414896
"?stopSleepInBed@Player@@UEAAX_N0@Z" = 63418624
"?take@Player@@QEAA_NAEAVActor@@HH@Z" = 63457616
"?teleportTo@Player@@UEAAXAEBVVec3@@_NHH1@Z" = 63410192
# RakNet::RNS2_Windows_Linux_360
"?Send_Windows_Linux_360NoVDP@RNS2_Windows_Linux_360@RakNet@@KAHHPEAURNS2_SendParameters@2@PEBDI@Z" = 77796512
# RakPeerHelper
"?peerStartup@RakPeerHelper@@QEAA?AW4StartupResult@RakNet@@PEAVRakPeerInterface@3@AEBUConnectionDefinition@@W4PeerPurpose@1@@Z" = 27188304
# RepositoryFactory
"?createSources@RepositoryFactory@@UEBA?AV?$shared_ptr@VRepositorySources@@@std@@AEBVIResourcePackRepository@@@Z" = 37423280
# RepositorySources
"?initializePackSource@RepositorySources@@QEAAXAEAVPackSourceFactory@@@Z" = 37387408
# ResourcePackStack
"?deserialize@ResourcePackStack@@SA?AV?$unique_ptr@VResourcePackStack@@U?$default_delete@VResourcePackStack@@@std@@@std@@AEAV?$basic_istream@DU?$char_traits@D@std@@@3@AEBV?$not_null@V?$NonOwnerPointer@$$CBVIResourcePackRepository@@@Bedrock@@@gsl@@V?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@3@@Z" = 36965680
# SayCommand
"?_sendMessage@SayCommand@@CAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@3@0AEBUCommandOriginIdentity@@AEAVLevel@@@Z" = 50045600
# ScriptModuleMinecraft::ScriptBlockUtils
"?createBlockDescriptor@ScriptBlockUtils@ScriptModuleMinecraft@@YA?AVBlockDescriptor@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@@std@@@2@@std@@@5@@Z" = 38996960
# ServerInstance
"?initializeServer@ServerInstance@@QEAA_N$$QEAUServerInstanceInitArguments@@@Z" = 49004208
# ServerNetworkHandler
"?_validateLoginPacket@ServerNetworkHandler@@EEAA?AV?$optional@UPlayerAuthenticationInfo@@@std@@AEBVNetworkIdentifier@@AEBVLoginPacket@@@Z" = 27389264
"?disconnectClientWithMessage@ServerNetworkHandler@@QEAAXAEBVNetworkIdentifier@@W4SubClientId@@W4DisconnectFailReason@Connection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@7@_N@Z" = 27345888
"?tryToLoadPlayer@ServerNetworkHandler@@QEAA_NAEAVServerPlayer@@AEBVConnectionRequest@@AEBUPlayerAuthenticationInfo@@@Z" = 27419104
"?updateServerAnnouncement@ServerNetworkHandler@@QEAAXXZ" = 27463696
# ServerPlayer
"?changeDimension@ServerPlayer@@UEAAXV?$AutomaticID@VDimension@@H@@@Z" = 49090848
# ServerPlayerMovementCorrectionSystem
"?_tickServerPlayerMovementCorrectionSystem@ServerPlayerMovementCorrectionSystem@@YAXAEBVStrictEntityContext@@AEBUServerPlayerCurrentMovementComponent@@AEBVUserEntityIdentifierComponent@@AEAUServerPlayerMovementComponent@@V?$Optional@$$CBUPassengerComponent@@@@AEAUStateVectorComponent@@AEBV?$ViewT@VStrictEntityContext@@$$CBUActorRotationComponent@@VActorOwnerComponent@@VReplayStateComponent@@UStateVectorComponent@@V?$Optional@$$CBUBoatMovementComponent@@@@@@@Z" = 23972816
# ServerScoreboard
"??0ServerScoreboard@@QEAA@VCommandSoftEnumRegistry@@PEAVLevelStorage@@V?$not_null@V?$NonOwnerPointer@VGameplayUserManager@@@Bedrock@@@gsl@@@Z" = 77674496
# UnverifiedCertificate
"?fromString@UnverifiedCertificate@@SA?AV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z" = 78177728
# WeatherManager
"?updateWeather@WeatherManager@@QEAAXMHMH@Z" = 70157552

[linux]
"BlockState::StateListNode::mHead" = 207796200
"Enchant::mEnchants" = 207628880
"getI18n::result" = 206713864
# Actor
"_ZN5Actor10teleportToERK4Vec3biib" = 152064144
# ActorFactory
"_ZN12ActorFactory18createSpawnedActorERK25ActorDefinitionIdentifierP5ActorRK4Vec3RK4Vec2" = 152687248
# BedrockLog::LogDetails
"_ZN10BedrockLog10LogDetails7_log_vaE9LogAreaIDjPKciiS3_P13__va_list_tag" = 200858208
# BlockDescriptor::ResolveHelper
"_ZN15BlockDescriptor13ResolveHelper7resolveEb" = 171832496
# BlockType
"_ZNK9BlockType25tryGetStateFromLegacyDataEt" = 170536448
# BlockTypeRegistry
"_ZN17BlockTypeRegistry16forEachBlockTypeEN5brstd12function_refIFbRK9BlockTypeES5_EE" = 175197216
# CampfireBlockActor
"_ZN18CampfireBlockActor14_finishCookingER11BlockSourcei" = 178154160
# Certificate
"_ZN11Certificate8validateElbb" = 184408192
# Command
"_ZNK7Command3runERK13CommandOriginR13CommandOutput" = 138056592
# CommandOriginLoader
"_ZN19CommandOriginLoader4loadERK11CompoundTagR11ServerLevel" = 137314032
# CommandRegistry
"_ZN15CommandRegistry13addEnumValuesERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_6vectorIS6_NS4_IS6_EEEE" = 137495376
"_ZN15CommandRegistry13registerAliasENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES6_" = 137511552
"_ZN15CommandRegistry15registerCommandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPKc22CommandPermissionLevel11CommandFlagSC_" = 137501664
"_ZN15CommandRegistry24registerOverloadInternalERNS_9SignatureERNS_8OverloadE" = 137515392
"_ZNK15CommandRegistry14symbolToStringENS_6SymbolE" = 137392640
"_ZNK15CommandRegistry26serializeAvailableCommandsEv" = 137577408
# CommandUtils
"_ZN12CommandUtils12getActorNameERK5Actor" = 137314768
# CraftingDataPacket
"_ZN18CraftingDataPacket18prepareFromRecipesERK7Recipesb" = 116403696
# DedicatedServer
"_ZN15DedicatedServer5startERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKN7Bedrock19ActivationArgumentsE" = 60923984
# FurnaceBlockActor
"_ZN17FurnaceBlockActor15getBurnDurationERK13ItemStackBasef" = 177926176
# InventoryTransaction
"_ZNK20InventoryTransaction11executeFullER6Playerb" = 168975616
# Item
"_ZNK4Item12readUserDataER13ItemStackBaseR10IDataInputR20ReadOnlyBinaryStream" = 168467376
# ItemInstance
"_ZN12ItemInstance7fromTagERK11CompoundTag" = 168551072
# ItemRegistry
"_ZNK12ItemRegistry12lookupByNameERiNSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE" = 163169520
# ItemStackBase
"_ZN13ItemStackBase34_loadBlocksForCanPlaceOnCanDestroyERNSt3__16vectorIPK9BlockTypeNS0_9allocatorIS4_EEEERKNS0_12basic_stringIcNS0_11char_traitsIcEENS5_IcEEEE" = 168605664
"_ZN13ItemStackBase4initEiiib" = 168574352
# LeavesBlock
"_ZN11LeavesBlock4_dieER11BlockSourceRK8BlockPos" = 169937936
# Level
"_ZN5Level4tickEv" = 173068912
# LiquidBlock
"_ZNK11LiquidBlock12_trySpreadToER11BlockSourceRK8BlockPosiS4_h" = 169832032
# MapDataManager
"_ZN14MapDataManager12_loadMapDataERK13ActorUniqueID" = 172764752
# MinecraftCommands
"_ZN17MinecraftCommands14compileCommandERK12HashedStringR13CommandOrigin17CurrentCmdVersionNSt3__18functionIFvRKNS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEEEE" = 137686832
"_ZNK17MinecraftCommands14executeCommandER14CommandContextb" = 137635552
# MinecraftPackets
"_ZN16MinecraftPackets12createPacketE18MinecraftPacketIds" = 118784576
# Mob
"_ZN3Mob9knockbackEP5Actorifffff" = 150540560
# NetworkConnection
"_ZN17NetworkConnection13receivePacketERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_10shared_ptrINS0_6chrono10time_pointINS9_12steady_clockENS9_8durationIxNS0_5ratioILl1ELl1000000000EEEEEEEEE" = 119123024
# NetworkSystem
"_ZN13NetworkSystem14sendToMultipleERKNSt3__16vectorI26NetworkIdentifierWithSubIdNS0_9allocatorIS2_EEEERK6Packet" = 118830352
"_ZN13NetworkSystem4sendERK17NetworkIdentifierRK6Packet11SubClientId" = 118793312
# Pack
"_ZN4Pack10createPackERK15IPackIOProviderRK16ResourceLocation8PackType10PackOriginR20IPackManifestFactoryN7Bedrock15NonOwnerPointerIK19IContentKeyProviderEEP16PackSourceReportRKN4Core4PathE" = 135749216
# PistonBlockActor
"_ZN16PistonBlockActor4tickER11BlockSource" = 178041392
# Player
"_ZN6Player10teleportToERK4Vec3biib" = 160051408
"_ZN6Player14stopSleepInBedEbb" = 160062400
"_ZN6Player15startSleepInBedERK8BlockPos" = 160058048
"_ZN6Player17completeUsingItemEv" = 160079440
"_ZN6Player4dropERK9ItemStackb" = 160190128
"_ZN6Player4takeER5Actorii" = 160137088
# RakNet::RNS2_Windows_Linux_360
"_ZN6RakNet22RNS2_Windows_Linux_36027Send_Windows_Linux_360NoVDPEiPNS_19RNS2_SendParametersEPKcj" = 183946432
# RakPeerHelper
"_ZN13RakPeerHelper11peerStartupEPN6RakNet16RakPeerInterfaceERK20ConnectionDefinitionNS_11PeerPurposeE" = 118908512
# RepositoryFactory
"_ZNK17RepositoryFactory13createSourcesERK23IResourcePackRepository" = 134931680
# RepositorySources
"_ZN17RepositorySources20initializePackSourceER17PackSourceFactory" = 135331600
# ResourcePackStack
"_ZN17ResourcePackStack11deserializeERNSt3__113basic_istreamIcNS0_11char_traitsIcEEEERKN3gsl8not_nullIN7Bedrock15NonOwnerPointerIK23IResourcePackRepositoryEEEENS0_8optionalINS0_12basic_stringIcS3_NS0_9allocatorIcEEEEEE" = 134811616
# SayCommand
"_ZN10SayCommand12_sendMessageERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_8optionalIS6_EES8_RK21CommandOriginIdentityR5Level" = 135897840
# ScriptModuleMinecraft::ScriptBlockUtils
"_ZN21ScriptModuleMinecraft16ScriptBlockUtils21createBlockDescriptorENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_8optionalINS1_13unordered_mapIS7_NS1_7variantIJiS7_bEEENS1_4hashIS7_EENS1_8equal_toIS7_EENS5_INS1_4pairIKS7_SB_EEEEEEEE" = 125649120
# ServerInstance
"_ZN14ServerInstance16initializeServerEO27ServerInstanceInitArguments" = 138245168
# ServerNetworkHandler
"_ZN20ServerNetworkHandler15tryToLoadPlayerER12ServerPlayerRK17ConnectionRequestRK24PlayerAuthenticationInfo" = 118198800
"_ZN20ServerNetworkHandler20_validateLoginPacketERK17NetworkIdentifierRK11LoginPacket" = 118131248
"_ZN20ServerNetworkHandler24updateServerAnnouncementEv" = 118118400
"_ZN20ServerNetworkHandler27disconnectClientWithMessageERK17NetworkIdentifier11SubClientIdN10Connection20DisconnectFailReasonERKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEENS6_8optionalISC_EEb" = 118067920
"_ZNK20ServerNetworkHandler20_isServerTextEnabledERK15ServerTextEvent" = 118119888
# ServerPlayer
"_ZN12ServerPlayer15changeDimensionE11AutomaticIDI9DimensioniE" = 137994256
# ServerPlayerMovementCorrectionSystem
"_ZN36ServerPlayerMovementCorrectionSystem41_tickServerPlayerMovementCorrectionSystemERK19StrictEntityContextRK36ServerPlayerCurrentMovementComponentRK29UserEntityIdentifierComponentR29ServerPlayerMovementComponent8OptionalIK18PassengerComponentER20StateVectorComponentRK5ViewTIS0_JK22ActorRotationComponent19ActorOwnerComponent20ReplayStateComponentSF_SB_IK21BoatMovementComponentEEE" = 104804480
# ServerScoreboard
"_ZN16ServerScoreboardC2E23CommandSoftEnumRegistryP12LevelStorageN3gsl8not_nullIN7Bedrock15NonOwnerPointerI19GameplayUserManagerEEEE" = 179322304
# UnverifiedCertificate
"_ZN21UnverifiedCertificate10fromStringERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE" = 184402400
# WeatherManager
"_ZN14WeatherManager13updateWeatherEfifi" = 172474800
