timestamp = 1764026426
version = "1.21.124"

[windows]
"BlockState::StateListNode::mHead" = 118038288
"Enchant::mEnchants" = 118434160
"getI18n::result" = 118579568
# Actor
"?teleportTo@Actor@@UEAAXAEBVVec3@@_NHH1@Z" = 54982608
# ActorFactory
"?createSpawnedActor@ActorFactory@@QEAA?AV?$OwnerPtr@VEntityContext@@@@AEBUActorDefinitionIdentifier@@PEAVActor@@AEBVVec3@@AEBVVec2@@@Z" = 55402784
# BedrockLog::LogDetails
"?_log_va@LogDetails@BedrockLog@@AEAAXW4LogAreaID@@IPEBDHH1PEAD@Z" = 91304304
# BlockDescriptor::ResolveHelper
"?resolve@ResolveHelper@BlockDescriptor@@QEAAX_N@Z" = 67906352
# BlockType
"?tryGetStateFromLegacyData@BlockType@@QEBAPEBVBlock@@G@Z" = 67646672
# BlockTypeRegistry
"?forEachBlockType@BlockTypeRegistry@@QEAAXV?$function_ref@$$A6A_NAEBVBlockType@@@Z$$A6A_N0@Z@brstd@@@Z" = 70322960
# CampfireBlockActor
"?_finishCooking@CampfireBlockActor@@AEAAXAEAVBlockSource@@H@Z" = 70112176
# Command
"?run@Command@@QEBAXAEBVCommandOrigin@@AEAVCommandOutput@@@Z" = 49434880
# CommandOriginLoader
"?load@CommandOriginLoader@@SA?AV?$unique_ptr@VCommandOrigin@@U?$default_delete@VCommandOrigin@@@std@@@std@@AEBVCompoundTag@@AEAVServerLevel@@@Z" = 48734672
# CommandRegistry
"?addEnumValues@CommandRegistry@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@3@@Z" = 48854752
"?describe@CommandRegistry@@AEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVCommandParameterData@@@Z" = 48866864
"?registerAlias@CommandRegistry@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z" = 48824624
"?registerCommand@CommandRegistry@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBDW4CommandPermissionLevel@@UCommandFlag@@3@Z" = 48821984
"?registerOverloadInternal@CommandRegistry@@AEAAXAEAUSignature@1@AEAUOverload@1@@Z" = 48830704
"?serializeAvailableCommands@CommandRegistry@@QEBA?AVAvailableCommandsPacket@@XZ" = 48877936
"?symbolToString@CommandRegistry@@AEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VSymbol@1@@Z" = 48873376
# CommandUtils
"?getActorName@CommandUtils@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActor@@@Z" = 48914592
# Common
"?getGameVersionString@Common@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ" = 9478672
# CraftingDataPacket
"?prepareFromRecipes@CraftingDataPacket@@SA?AV?$unique_ptr@VCraftingDataPacket@@U?$default_delete@VCraftingDataPacket@@@std@@@std@@AEBVRecipes@@_N@Z" = 23552976
# DedicatedServer
"?start@DedicatedServer@@QEAA?AW4StartResult@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActivationArguments@Bedrock@@@Z" = 1229200
# FurnaceBlockActor
"?getBurnDuration@FurnaceBlockActor@@SAMAEBVItemStackBase@@M@Z" = 70842768
# HealthAttributeDelegate
"?change@HealthAttributeDelegate@@UEAAMMMAEBVAttributeBuff@@@Z" = 61331008
# InventoryTransaction
"?executeFull@InventoryTransaction@@QEBA?AW4InventoryTransactionError@@AEAVPlayer@@_N@Z" = 63535008
# Item
"?readUserData@Item@@UEBAXAEAVItemStackBase@@AEAVIDataInput@@AEAVReadOnlyBinaryStream@@@Z" = 62810000
# ItemInstance
"?fromTag@ItemInstance@@SA?AV1@AEBVCompoundTag@@@Z" = 61610048
# ItemRegistry
"?lookupByName@ItemRegistry@@AEBA?AV?$WeakPtr@VItem@@@@AEAHV?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z" = 61514288
# ItemStackBase
"?_loadBlocksForCanPlaceOnCanDestroy@ItemStackBase@@CA_NAEAV?$vector@PEBVBlockType@@V?$allocator@PEBVBlockType@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z" = 61670512
"?init@ItemStackBase@@IEAAXHHH_N@Z" = 61628656
# LeavesBlock
"?_die@LeavesBlock@@IEBAXAEAVBlockSource@@AEBVBlockPos@@@Z" = 68285632
# Level
"?tick@Level@@UEAAXXZ" = 66950992
# MapDataManager
"?_loadMapData@MapDataManager@@IEAAPEAVMapItemSavedData@@AEBUActorUniqueID@@@Z" = 67143616
# MinecraftCommands
"?compileCommand@MinecraftCommands@@QEAAPEAVCommand@@AEBVHashedString@@AEAVCommandOrigin@@W4CurrentCmdVersion@@V?$function@$$A6AXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@std@@@Z" = 48954160
"?executeCommand@MinecraftCommands@@QEBA?AUMCRESULT@@AEAVCommandContext@@_N@Z" = 48951680
# MinecraftPackets
"?createPacket@MinecraftPackets@@SA?AV?$shared_ptr@VPacket@@@std@@W4MinecraftPacketIds@@@Z" = 20236128
# Mob
"?_hurt@Mob@@MEAA_NAEBVActorDamageSource@@M_N1@Z" = 57327696
"?knockback@Mob@@UEAAXPEAVActor@@HMMMMM@Z" = 57331344
# NetworkConnection
"?receivePacket@NetworkConnection@@QEAA?AW4DataStatus@NetworkPeer@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$shared_ptr@V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@@5@@Z" = 21513696
# NetworkSystem
"?send@NetworkSystem@@QEAAXAEBVNetworkIdentifier@@AEBVPacket@@W4SubClientId@@@Z" = 20233600
"?sendToMultiple@NetworkSystem@@QEAAXAEBV?$vector@UNetworkIdentifierWithSubId@@V?$allocator@UNetworkIdentifierWithSubId@@@std@@@std@@AEBVPacket@@@Z" = 20234608
# Pack
"?createPack@Pack@@SA?AV?$unique_ptr@VPack@@U?$default_delete@VPack@@@std@@@std@@AEBVIPackIOProvider@@AEBVResourceLocation@@W4PackType@@W4PackOrigin@@AEAVIPackManifestFactory@@V?$NonOwnerPointer@$$CBVIContentKeyProvider@@@Bedrock@@PEAVPackSourceReport@@AEBVPath@Core@@@Z" = 33330752
# PistonBlockActor
"?tick@PistonBlockActor@@UEAAXAEAVBlockSource@@@Z" = 71071712
# Player
"?completeUsingItem@Player@@QEAAXXZ" = 59800800
"?drop@Player@@UEAA_NAEBVItemStack@@_N@Z" = 59858528
"?startSleepInBed@Player@@UEAA?AW4BedSleepingResult@@AEBVBlockPos@@@Z" = 59783568
"?stopSleepInBed@Player@@UEAAX_N0@Z" = 59786960
"?take@Player@@QEAA_NAEAVActor@@HH@Z" = 59824240
"?teleportTo@Player@@UEAAXAEBVVec3@@_NHH1@Z" = 59778976
# RakNet::RNS2_Windows_Linux_360
"?Send_Windows_Linux_360NoVDP@RNS2_Windows_Linux_360@RakNet@@KAHHPEAURNS2_SendParameters@2@PEBDI@Z" = 75314512
# RakPeerHelper
"?peerStartup@RakPeerHelper@@QEAA?AW4StartupResult@RakNet@@PEAVRakPeerInterface@3@AEBUConnectionDefinition@@W4PeerPurpose@1@@Z" = 20297312
# RepositoryFactory
"?createSources@RepositoryFactory@@UEBA?AV?$shared_ptr@VRepositorySources@@@std@@AEBVIResourcePackRepository@@@Z" = 33817888
# RepositorySources
"?initializePackSource@RepositorySources@@QEAAXAEAVPackSourceFactory@@@Z" = 33552000
# ResourcePackStack
"?deserialize@ResourcePackStack@@SA?AV?$unique_ptr@VResourcePackStack@@U?$default_delete@VResourcePackStack@@@std@@@std@@AEAV?$basic_istream@DU?$char_traits@D@std@@@3@AEBV?$not_null@V?$NonOwnerPointer@$$CBVIResourcePackRepository@@@Bedrock@@@gsl@@V?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@3@@Z" = 33852880
# SayCommand
"?_sendMessage@SayCommand@@CAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@3@0AEBUCommandOriginIdentity@@AEAVLevel@@@Z" = 51654848
# ScriptModuleMinecraft::ScriptBlockUtils
"?createBlockDescriptor@ScriptBlockUtils@ScriptModuleMinecraft@@YA?AVBlockDescriptor@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@@std@@@2@@std@@@5@@Z" = 38399360
# ServerNetworkHandler
"?_createNewPlayer@ServerNetworkHandler@@AEAAAEAVServerPlayer@@AEBVNetworkIdentifier@@AEBVSubClientConnectionRequest@@W4SubClientId@@@Z" = 20632336
"?_isServerTextEnabled@ServerNetworkHandler@@AEBA_NAEBW4ServerTextEvent@@@Z" = 20640992
"?disconnectClientWithMessage@ServerNetworkHandler@@QEAAXAEBVNetworkIdentifier@@W4SubClientId@@W4DisconnectFailReason@Connection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@7@_N@Z" = 20494352
"?trytLoadPlayer@ServerNetworkHandler@@QEAA_NAEAVServerPlayer@@AEBVConnectionRequest@@@Z" = 20569216
"?updateServerAnnouncement@ServerNetworkHandler@@QEAAXXZ" = 20611760
# ServerPlayer
"?changeDimension@ServerPlayer@@UEAAXV?$AutomaticID@VDimension@@H@@@Z" = 49383376
# ServerPlayerMovementCorrectionSystem
"?_afterMovementSimulation@ServerPlayerMovementCorrectionSystem@@YAXAEBVUserEntityIdentifierComponent@@AEAVActor@@AEBVPlayerAuthInputPacket@@AEAVReplayStateComponent@@PEBUActorRotationComponent@@AEAUServerPlayerMovementComponent@@AEAUStateVectorComponent@@PEBUBoatMovementComponent@@@Z" = 17125552
# ServerScoreboard
"??0ServerScoreboard@@QEAA@VCommandSoftEnumRegistry@@PEAVLevelStorage@@V?$not_null@V?$NonOwnerPointer@VGameplayUserManager@@@Bedrock@@@gsl@@@Z" = 73517760
# ServerScriptManager
"?_runPlugins@ServerScriptManager@@AEAAXW4PluginExecutionGroup@@AEAVServerInstance@@@Z" = 34021952
# UnverifiedCertificate
"?fromString@UnverifiedCertificate@@SA?AV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z" = 9484752
# GameRules
"?_setGameRule@GameRules@@AEAA?AV?$unique_ptr@VGameRulesChangedPacket@@U?$default_delete@VGameRulesChangedPacket@@@std@@@std@@PEAVGameRule@@V?$variant@Umonostate@std@@_NHM@3@W4Type@4@_NPEA_N4PEAVValidationError@4@@Z" = 73277792

[linux]
"BlockState::StateListNode::mHead" = 221392056
"Enchant::mEnchants" = 221257264
"_Z7getI18nv" = 91129792
# Actor
"_ZN5Actor10teleportToERK4Vec3biib" = 157512912
# ActorFactory
"_ZN12ActorFactory18createSpawnedActorERK25ActorDefinitionIdentifierP5ActorRK4Vec3RK4Vec2" = 157783600
# BedrockLog::LogDetails
"_ZN10BedrockLog10LogDetails7_log_vaE9LogAreaIDjPKciiS3_P13__va_list_tag" = 212302768
# BlockDescriptor::ResolveHelper
"_ZN15BlockDescriptor13ResolveHelper7resolveEb" = 175214208
# BlockType
"_ZNK9BlockType25tryGetStateFromLegacyDataEt" = 175058096
# BlockTypeRegistry
"_ZN17BlockTypeRegistry16forEachBlockTypeEN5brstd12function_refIFbRK9BlockTypeES5_EE" = 179448144
# CampfireBlockActor
"_ZN18CampfireBlockActor14_finishCookingER11BlockSourcei" = 182576176
# Command
"_ZNK7Command3runERK13CommandOriginR13CommandOutput" = 147763024
# CommandOriginLoader
"_ZN19CommandOriginLoader4loadERK11CompoundTagR11ServerLevel" = 146940816
# CommandRegistry
"_ZN15CommandRegistry13addEnumValuesERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_6vectorIS6_NS4_IS6_EEEE" = 147113008
"_ZN15CommandRegistry13registerAliasENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES6_" = 147121456
"_ZN15CommandRegistry15registerCommandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPKc22CommandPermissionLevel11CommandFlagSC_" = 147115616
"_ZN15CommandRegistry24registerOverloadInternalERNS_9SignatureERNS_8OverloadE" = 147123984
"_ZNK15CommandRegistry14symbolToStringENS_6SymbolE" = 147017760
"_ZNK15CommandRegistry26serializeAvailableCommandsEv" = 147211216
"_ZNK15CommandRegistry8describeERK20CommandParameterData" = 147191920
# CommandUtils
"_ZN12CommandUtils12getActorNameERK5Actor" = 146934144
# Common
"_ZN6Common20getGameVersionStringEv" = 83997072
# CraftingDataPacket
"_ZN18CraftingDataPacket18prepareFromRecipesERK7Recipesb" = 117031536
# DedicatedServer
"_ZN15DedicatedServer5startERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKN7Bedrock19ActivationArgumentsE" = 63650816
# FurnaceBlockActor
"_ZN17FurnaceBlockActor15getBurnDurationERK13ItemStackBasef" = 182410224
# HealthAttributeDelegate
"_ZN23HealthAttributeDelegate6changeEffRK13AttributeBuff" = 164892048
# InventoryTransaction
"_ZNK20InventoryTransaction11executeFullER6Playerb" = 173689760
# Item
"_ZNK4Item12readUserDataER13ItemStackBaseR10IDataInputR20ReadOnlyBinaryStream" = 173381424
# ItemInstance
"_ZN12ItemInstance7fromTagERK11CompoundTag" = 173108608
# ItemRegistry
"_ZNK12ItemRegistry12lookupByNameERiNSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE" = 167924480
# ItemStackBase
"_ZN13ItemStackBase34_loadBlocksForCanPlaceOnCanDestroyERNSt3__16vectorIPK9BlockTypeNS0_9allocatorIS4_EEEERKNS0_12basic_stringIcNS0_11char_traitsIcEENS5_IcEEEE" = 173174432
"_ZN13ItemStackBase4initEiiib" = 173132560
# LeavesBlock
"_ZNK11LeavesBlock4_dieER11BlockSourceRK8BlockPos" = 174572320
# Level
"_ZN5Level4tickEv" = 177309408
# MapDataManager
"_ZN14MapDataManager12_loadMapDataERK13ActorUniqueID" = 177000896
# MinecraftCommands
"_ZN17MinecraftCommands14compileCommandERK12HashedStringR13CommandOrigin17CurrentCmdVersionNSt3__18functionIFvRKNS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEEEE" = 147294416
"_ZNK17MinecraftCommands14executeCommandER14CommandContextb" = 147261904
# MinecraftPackets
"_ZN16MinecraftPackets12createPacketE18MinecraftPacketIds" = 120204208
# Mob
"_ZN3Mob5_hurtERK17ActorDamageSourcefbb" = 156310576
"_ZN3Mob9knockbackEP5Actorifffff" = 156313840
# NetworkConnection
"_ZN17NetworkConnection13receivePacketERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_10shared_ptrINS0_6chrono10time_pointINS9_12steady_clockENS9_8durationIxNS0_5ratioILl1ELl1000000000EEEEEEEEE" = 120552720
# NetworkSystem
"_ZN13NetworkSystem14sendToMultipleERKNSt3__16vectorI26NetworkIdentifierWithSubIdNS0_9allocatorIS2_EEEERK6Packet" = 120240080
"_ZN13NetworkSystem4sendERK17NetworkIdentifierRK6Packet11SubClientId" = 120194384
# Pack
"_ZN4Pack10createPackERK15IPackIOProviderRK16ResourceLocation8PackType10PackOriginR20IPackManifestFactoryN7Bedrock15NonOwnerPointerIK19IContentKeyProviderEEP16PackSourceReportRKN4Core4PathE" = 141761600
# PistonBlockActor
"_ZN16PistonBlockActor4tickER11BlockSource" = 181492016
# Player
"_ZN6Player10teleportToERK4Vec3biib" = 165492000
"_ZN6Player14stopSleepInBedEbb" = 165498928
"_ZN6Player15startSleepInBedERK8BlockPos" = 165495744
"_ZN6Player17completeUsingItemEv" = 165510000
"_ZN6Player4dropERK9ItemStackb" = 165580672
"_ZN6Player4takeER5Actorii" = 165540320
# RakNet::RNS2_Windows_Linux_360
"_ZN6RakNet22RNS2_Windows_Linux_36027Send_Windows_Linux_360NoVDPEiPNS_19RNS2_SendParametersEPKcj" = 187991824
# RakPeerHelper
"_ZN13RakPeerHelper11peerStartupEPN6RakNet16RakPeerInterfaceERK20ConnectionDefinitionNS_11PeerPurposeE" = 120266560
# RepositoryFactory
"_ZNK17RepositoryFactory13createSourcesERK23IResourcePackRepository" = 141644112
# RepositorySources
"_ZN17RepositorySources20initializePackSourceER17PackSourceFactory" = 141977840
# ResourcePackStack
"_ZN17ResourcePackStack11deserializeERNSt3__113basic_istreamIcNS0_11char_traitsIcEEEERKN3gsl8not_nullIN7Bedrock15NonOwnerPointerIK23IResourcePackRepositoryEEEENS0_8optionalINS0_12basic_stringIcS3_NS0_9allocatorIcEEEEEE" = 141436016
# SayCommand
"_ZN10SayCommand12_sendMessageERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_8optionalIS6_EES8_RK21CommandOriginIdentityR5Level" = 145777808
# ScriptModuleMinecraft::ScriptBlockUtils
"_ZN21ScriptModuleMinecraft16ScriptBlockUtils21createBlockDescriptorENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_8optionalINS1_13unordered_mapIS7_NS1_7variantIJiS7_bEEENS1_4hashIS7_EENS1_8equal_toIS7_EENS5_INS1_4pairIKS7_SB_EEEEEEEE" = 132094240
# ServerNetworkHandler
"_ZN20ServerNetworkHandler14trytLoadPlayerER12ServerPlayerRK17ConnectionRequest" = 119216320
"_ZN20ServerNetworkHandler16_createNewPlayerERK17NetworkIdentifierRK26SubClientConnectionRequest11SubClientId" = 119253296
"_ZN20ServerNetworkHandler24updateServerAnnouncementEv" = 119162112
"_ZN20ServerNetworkHandler27disconnectClientWithMessageERK17NetworkIdentifier11SubClientIdN10Connection20DisconnectFailReasonERKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEENS6_8optionalISC_EEb" = 119130592
"_ZNK20ServerNetworkHandler20_isServerTextEnabledERK15ServerTextEvent" = 119162912
# ServerPlayer
"_ZN12ServerPlayer15changeDimensionE11AutomaticIDI9DimensioniE" = 147702880
# ServerPlayerMovementCorrectionSystem
"_ZN36ServerPlayerMovementCorrectionSystem24_afterMovementSimulationERK29UserEntityIdentifierComponentR5ActorRK21PlayerAuthInputPacketR20ReplayStateComponentPK22ActorRotationComponentR29ServerPlayerMovementComponentR20StateVectorComponentPK21BoatMovementComponent" = 104290576
# ServerScoreboard
"_ZN16ServerScoreboardC2E23CommandSoftEnumRegistryP12LevelStorageN3gsl8not_nullIN7Bedrock15NonOwnerPointerI19GameplayUserManagerEEEE" = 183485056
# ServerScriptManager
"_ZN19ServerScriptManager11_runPluginsE20PluginExecutionGroupR14ServerInstance" = 140473952
# UnverifiedCertificate
"_ZN21UnverifiedCertificate10fromStringERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE" = 84003200
