timestamp = 1726073578
version = "1.21.20"

[windows]
"?getI18n@@YAAEAVI18n@@XZ" = 8433040
# Actor
"?remove@Actor@@UEAAXXZ" = 27022784
"?teleportTo@Actor@@UEAAXAEBVVec3@@_NHH1@Z" = 27052128
# Bedrock
"?getServerThread@Threading@Bedrock@@YAAEAVAssignedThread@12@XZ" = 44934560
# BedrockLog
"?log_va@BedrockLog@@YAXW4LogCategory@1@V?$bitset@$02@std@@W4LogRule@1@W4LogAreaID@@IPEBDH4PEAD@Z" = 42675472
# BlockDescriptor
"?tryGetBlockNoLogging@BlockDescriptor@@QEBAPEBVBlock@@XZ" = 29145776
# BlockTypeRegistry
"?forEachBlock@BlockTypeRegistry@@SAXV?$function@$$A6A_NAEBVBlockLegacy@@@Z@std@@@Z" = 34338112
# Command
"?getCommandName@Command@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ" = 13128016
# CommandOriginLoader
"?load@CommandOriginLoader@@SA?AV?$unique_ptr@VCommandOrigin@@U?$default_delete@VCommandOrigin@@@std@@@std@@AEBVCompoundTag@@AEAVServerLevel@@@Z" = 13148224
# CommandOutput
"?addMessage@CommandOutput@@AEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@VCommandOutputParameter@@V?$allocator@VCommandOutputParameter@@@std@@@3@W4CommandOutputMessageType@@@Z" = 13105328
# CommandRegistry
"?addEnumValues@CommandRegistry@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@3@@Z" = 13642416
"?createCommand@CommandRegistry@@AEBA?AV?$unique_ptr@VCommand@@U?$default_delete@VCommand@@@std@@@std@@AEBUParseToken@1@AEBVCommandOrigin@@HAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@AEAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@3@@Z" = 13661024
"?describe@CommandRegistry@@AEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVCommandParameterData@@@Z" = 13662976
"?describe@CommandRegistry@@AEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBUSignature@1@AEBV23@AEBUOverload@1@IPEAI3@Z" = 13662336
"?findCommand@CommandRegistry@@AEBAPEBUSignature@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z" = 13668304
"?registerAlias@CommandRegistry@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z" = 13694352
"?registerCommand@CommandRegistry@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBDW4CommandPermissionLevel@@UCommandFlag@@3@Z" = 13695824
"?registerOverloadInternal@CommandRegistry@@AEAAXAEAUSignature@1@AEAUOverload@1@@Z" = 13697968
"?serializeAvailableCommands@CommandRegistry@@QEBA?AVAvailableCommandsPacket@@XZ" = 13702800
# CommandUtils
"?getActorName@CommandUtils@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActor@@@Z" = 13391504
# Common
"?getGameVersionString@Common@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ" = 5364368
# CraftingDataPacket
"?prepareFromRecipes@CraftingDataPacket@@SA?AV?$unique_ptr@VCraftingDataPacket@@U?$default_delete@VCraftingDataPacket@@@std@@@std@@AEBVRecipes@@_N@Z" = 8782704
# CreativeItemRegistry
"?forEachCreativeItemInstance@CreativeItemRegistry@@SAXV?$function@$$A6A_NAEAVItemInstance@@@Z@std@@@Z" = 28252960
# FurnaceBlockActor
"?getBurnDuration@FurnaceBlockActor@@SAMAEBVItemStackBase@@M@Z" = 37060512
# GameMode
"?destroyBlock@GameMode@@UEAA_NAEBVBlockPos@@E@Z" = 26498448
"?interact@GameMode@@UEAA_NAEAVActor@@AEBVVec3@@@Z" = 26508000
"?useItemOn@GameMode@@UEAA?AVInteractionResult@@AEAVItemStack@@AEBVBlockPos@@EAEBVVec3@@PEBVBlock@@@Z" = 26535680
# Item
"?_sendTryPlaceBlockEvent@Item@@IEBA?AW4CoordinatorResult@@AEBVBlock@@AEBVBlockSource@@AEBVActor@@AEBVBlockPos@@EAEBVVec3@@@Z" = 30340288
# ItemStack
"??0ItemStack@@QEAA@AEBVItem@@HHPEBVCompoundTag@@@Z" = 28697056
# Level
"?tick@Level@@UEAAXXZ" = 28146048
"?_getGameplayUserManagerStackRef@Level@@IEAA?AV?$not_null@V?$StackRefResult@VGameplayUserManager@@@@@gsl@@XZ" = 28078208
# MinecraftCommands
"?executeCommand@MinecraftCommands@@QEBA?AUMCRESULT@@AEAVCommandContext@@_N@Z" = 13388256
# MinecraftPackets
"?createPacket@MinecraftPackets@@SA?AV?$shared_ptr@VPacket@@@std@@W4MinecraftPacketIds@@@Z" = 8257984
# Mob
"?die@Mob@@UEAAXAEBVActorDamageSource@@@Z" = 26280064
"?knockback@Mob@@UEAAXPEAVActor@@HMMMMM@Z" = 26322464
# Player
"?getInventory@Player@@QEAAAEAVContainer@@XZ" = 27130976
"?getName@Player@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ" = 27132848
"?setPermissions@Player@@QEAAXW4CommandPermissionLevel@@@Z" = 27169792
"?teleportTo@Player@@UEAAXAEBVVec3@@_NHH1@Z" = 27184256
# PlayerEventCoordinator
"?sendEvent@PlayerEventCoordinator@@QEAAXAEBV?$EventRef@U?$PlayerGameplayEvent@X@@@@@Z" = 25937808
# RakNet
"?Send_Windows_Linux_360NoVDP@RNS2_Windows_Linux_360@RakNet@@KAHHPEAURNS2_SendParameters@2@PEBDI@Z" = 37542560
"?ToString@SystemAddress@RakNet@@QEBAX_NPEADD@Z" = 37404752
# RakPeerHelper
"?peerStartup@RakPeerHelper@@QEAA?AW4StartupResult@RakNet@@PEAVRakPeerInterface@3@AEBUConnectionDefinition@@W4PeerPurpose@1@@Z" = 8309504
# SayCommand
"?_sendMessage@SayCommand@@CAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@3@0AEBUCommandOriginIdentity@@AEAVLevel@@@Z" = 23835344
# Scoreboard
"?resetPlayerScore@Scoreboard@@QEAA_NAEBUScoreboardId@@AEAVObjective@@@Z" = 37359680
# ScriptModuleMinecraft::ScriptBlockUtils
"?createBlockDescriptor@ScriptBlockUtils@ScriptModuleMinecraft@@YA?AVBlockDescriptor@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@@std@@@2@@std@@@5@@Z" = 23370448
# ScriptLevelGameplayHandler
"?handleEvent@ScriptLevelGameplayHandler@@UEAA?AU?$GameplayHandlerResult@W4CoordinatorResult@@@@AEAULevelWeatherChangedEvent@@@Z" = 18138832
# ServerInstanceEventCoordinator
"?sendServerInitializeStart@ServerInstanceEventCoordinator@@QEAAXAEAVServerInstance@@@Z" = 25942224
"?sendServerLevelInitialized@ServerInstanceEventCoordinator@@QEAAXAEAVServerInstance@@AEAVLevel@@@Z" = 25942272
"?sendServerThreadStarted@ServerInstanceEventCoordinator@@QEAAXAEAVServerInstance@@@Z" = 25942560
"?sendServerThreadStopped@ServerInstanceEventCoordinator@@QEAAXAEAVServerInstance@@@Z" = 25942608
# ServerLevel
"?_postReloadActorAdded@ServerLevel@@AEAAXAEAVActor@@@Z" = 25868480
# ServerNetworkHandler
"?disconnectClient@ServerNetworkHandler@@QEAAXAEBVNetworkIdentifier@@W4SubClientId@@W4DisconnectFailReason@Connection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@7@_N@Z" = 8716128
"?trytLoadPlayer@ServerNetworkHandler@@QEAA_NAEAVServerPlayer@@AEBVConnectionRequest@@@Z" = 8796032
"?updateServerAnnouncement@ServerNetworkHandler@@QEAAXXZ" = 8797408
"?_createNewPlayer@ServerNetworkHandler@@AEAAAEAVServerPlayer@@AEBVNetworkIdentifier@@AEBVSubClientConnectionRequest@@W4SubClientId@@@Z" = 8621792
"?_displayGameMessage@ServerNetworkHandler@@AEAAXAEBVPlayer@@AEAUChatEvent@@@Z" = 8625728
"?_isServerTextEnabled@ServerNetworkHandler@@AEBA_NAEBW4ServerTextEvent@@@Z" = 8632224
# ServerPlayer
"?die@ServerPlayer@@UEAAXAEBVActorDamageSource@@@Z" = 13114944
"?disconnect@ServerPlayer@@QEAAXXZ" = 13115104
"?setLocalPlayerAsInitialized@ServerPlayer@@QEAAXXZ" = 13183024
# ServerScoreboard
"??0ServerScoreboard@@QEAA@VCommandSoftEnumRegistry@@PEAVLevelStorage@@AEBV?$not_null@V?$StackRefResult@VGameplayUserManager@@@@@gsl@@@Z" = 37334496
# StartGamePacket
"?write@StartGamePacket@@UEBAXAEAVBinaryStream@@@Z" = 10122208
# TeleportCommand
"?applyTarget@TeleportCommand@@SAXAEAVActor@@VTeleportTarget@@_N@Z" = 24257584
"?computeTarget@TeleportCommand@@SA?AVTeleportTarget@@AEAVActor@@VVec3@@PEAV4@V?$AutomaticID@VDimension@@H@@AEBV?$optional@VRotationData@RotationCommandUtils@@@std@@H@Z" = 24258080

[linux]
"_Z7getI18nv" = 74249008
# Actor
"_ZN5Actor6removeEv" = 110699280
"_ZN5Actor10teleportToERK4Vec3biib" = 110726368
# Bedrock
"_ZN7Bedrock9Threading15getServerThreadEv" = 142197856
# BedrockLog
"_ZN10BedrockLog6log_vaENS_11LogCategoryENSt3__16bitsetILm3EEENS_7LogRuleE9LogAreaIDjPKciS7_P13__va_list_tag" = 138934608
# BlockDescriptor
"_ZNK15BlockDescriptor20tryGetBlockNoLoggingEv" = 120408976
# BlockTypeRegistry
"_ZN17BlockTypeRegistry12forEachBlockENSt3__18functionIFbRK11BlockLegacyEEE" = 125367520
# Command
"_ZNK7Command14getCommandNameEv" = 97925040
# CommandOriginLoader
"_ZN19CommandOriginLoader4loadERK11CompoundTagR11ServerLevel" = 97974320
# CommandOutput
"_ZN13CommandOutput10addMessageERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_6vectorI22CommandOutputParameterNS4_ISA_EEEE24CommandOutputMessageType" = 97988384
# CommandRegistry
"_ZN15CommandRegistry13addEnumValuesERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_6vectorIS6_NS4_IS6_EEEE" = 91136768
"_ZNK15CommandRegistry13createCommandERKNS_10ParseTokenERK13CommandOriginiRNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEERNS6_6vectorISC_NSA_ISC_EEEE" = 91023552
"_ZNK15CommandRegistry8describeERK20CommandParameterData" = 91211872
"_ZNK15CommandRegistry8describeERKNS_9SignatureERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEERKNS_8OverloadEjPjSF_" = 91213520
"_ZNK15CommandRegistry11findCommandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE" = 91032992
"_ZN15CommandRegistry13registerAliasENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES6_" = 91144736
"_ZN15CommandRegistry15registerCommandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPKc22CommandPermissionLevel11CommandFlagSC_" = 91139376
"_ZN15CommandRegistry24registerOverloadInternalERNS_9SignatureERNS_8OverloadE" = 91156080
"_ZNK15CommandRegistry26serializeAvailableCommandsEv" = 91230624
# CommandUtils
"_ZN12CommandUtils12getActorNameERK5Actor" = 88557264
# Common
"_ZN6Common20getGameVersionStringEv" = 65264140
# CraftingDataPacket
"_ZN18CraftingDataPacket18prepareFromRecipesERK7Recipesb" = 79294224
# CreativeItemRegistry
"_ZN20CreativeItemRegistry27forEachCreativeItemInstanceENSt3__18functionIFbR12ItemInstanceEEE" = 118194976
# FurnaceBlockActor
"_ZN17FurnaceBlockActor15getBurnDurationERK13ItemStackBasef" = 129069424
# GameMode
"_ZN8GameMode12destroyBlockERK8BlockPosh" = 110952224
"_ZN8GameMode8interactER5ActorRK4Vec3" = 110948240
"_ZN8GameMode9useItemOnER9ItemStackRK8BlockPoshRK4Vec3PK5Block" = 110960672
# Item
"_ZNK4Item23_sendTryPlaceBlockEventERK5BlockRK11BlockSourceRK5ActorRK8BlockPoshRK4Vec3" = 118908352
# ItemStack
"_ZN9ItemStackC2ERK4ItemiiPK11CompoundTag" = 119795904
# Level
"_ZN5Level4tickEv" = 119240880
"_ZN5Level31_getGameplayUserManagerStackRefEv" = 119268720
# MinecraftCommands
"_ZNK17MinecraftCommands14executeCommandER14CommandContextb" = 88576496
# MinecraftPackets
"_ZN16MinecraftPackets12createPacketE18MinecraftPacketIds" = 77701376
# Mob
"_ZN3Mob3dieERK17ActorDamageSource" = 108022144
"_ZN3Mob9knockbackEP5Actorifffff" = 108021376
# Player
"_ZN6Player12getInventoryEv" = 110167008
"_ZNK6Player7getNameEv" = 110093264
"_ZN6Player14setPermissionsE22CommandPermissionLevel" = 110117632
"_ZN6Player10teleportToERK4Vec3biib" = 110083184
# PlayerEventCoordinator
"_ZN22PlayerEventCoordinator9sendEventERK8EventRefI19PlayerGameplayEventIvEE" = 112041280
# RakNet
"_ZN6RakNet22RNS2_Windows_Linux_36027Send_Windows_Linux_360NoVDPEiPNS_19RNS2_SendParametersEPKcj" = 130971840
"_ZNK6RakNet13SystemAddress8ToStringEbPcc" = 131005008
# RakPeerHelper
"_ZN13RakPeerHelper11peerStartupEPN6RakNet16RakPeerInterfaceERK20ConnectionDefinitionNS_11PeerPurposeE" = 77769696
# SayCommand
"_ZN10SayCommand12_sendMessageERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_8optionalIS6_EES8_RK21CommandOriginIdentityR5Level" = 80745232
# Scoreboard
"_ZN10Scoreboard16resetPlayerScoreERK12ScoreboardIdR9Objective" = 130373440
# ScriptModuleMinecraft::ScriptBlockUtils
"_ZN21ScriptModuleMinecraft16ScriptBlockUtils21createBlockDescriptorENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_8optionalINS1_13unordered_mapIS7_NS1_7variantIJiS7_bEEENS1_4hashIS7_EENS1_8equal_toIS7_EENS5_INS1_4pairIKS7_SB_EEEEEEEE" = 91834448
# ScriptLevelGameplayHandler
"_ZN26ScriptLevelGameplayHandler11handleEventER24LevelWeatherChangedEvent" = 95061536
# ServerInstanceEventCoordinator
"_ZN30ServerInstanceEventCoordinator25sendServerInitializeStartER14ServerInstance" = 112050144
"_ZN30ServerInstanceEventCoordinator26sendServerLevelInitializedER14ServerInstanceR5Level" = 112050576
"_ZN30ServerInstanceEventCoordinator23sendServerThreadStartedER14ServerInstance" = 112051296
"_ZN30ServerInstanceEventCoordinator23sendServerThreadStoppedER14ServerInstance" = 112051440
# ServerLevel
"_ZN11ServerLevel21_postReloadActorAddedER5Actor" = 112039232
# ServerNetworkHandler
"_ZN20ServerNetworkHandler16disconnectClientERK17NetworkIdentifier11SubClientIdN10Connection20DisconnectFailReasonERKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEENS6_8optionalISC_EEb" = 79189440
"_ZN20ServerNetworkHandler14trytLoadPlayerER12ServerPlayerRK17ConnectionRequest" = 79256768
"_ZN20ServerNetworkHandler24updateServerAnnouncementEv" = 79216448
"_ZN20ServerNetworkHandler16_createNewPlayerERK17NetworkIdentifierRK26SubClientConnectionRequest11SubClientId" = 79297792
"_ZN20ServerNetworkHandler19_displayGameMessageERK6PlayerR9ChatEvent" = 79181600
"_ZNK20ServerNetworkHandler20_isServerTextEnabledERK15ServerTextEvent" = 79217328
# ServerPlayer
"_ZN12ServerPlayer3dieERK17ActorDamageSource" = 98651120
"_ZN12ServerPlayer10disconnectEv" = 97881360
"_ZN12ServerPlayer27setLocalPlayerAsInitializedEv" = 97887520
# ServerScoreboard
"_ZN16ServerScoreboardC2E23CommandSoftEnumRegistryP12LevelStorageRKN3gsl8not_nullI14StackRefResultI19GameplayUserManagerEEE" = 130383072
# StartGamePacket
"_ZNK15StartGamePacket5writeER12BinaryStream" = 78817024
# TeleportCommand
"_ZN15TeleportCommand11applyTargetER5Actor14TeleportTargetb" = 89103552
"_ZN15TeleportCommand13computeTargetER5Actor4Vec3PS2_11AutomaticIDI9DimensioniERKNSt3__18optionalIN20RotationCommandUtils12RotationDataEEEi" = 89103936